name: CI (Linux)

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        include:
          - compiler: gcc
            cc: gcc
            cxx: g++
            archopts: -U_FORTIFY_SOURCE
          - compiler: clang
            cc: clang
            cxx: clang++
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev libasound2-dev libxinerama-dev libxi-dev qt5-default
      - name: Install clang
        if: matrix.compiler == 'clang'
        run: sudo apt-get install -y clang
      - name: Build
        env:
          OVERRIDE_CC: ${{ matrix.cc }}
          OVERRIDE_CXX: ${{ matrix.cxx }}
          ARCHOPTS: ${{ matrix.archopts }}
          TOOLS: 1
        run: make -j2
      - name: Validate
        run: ./mame -validate
      - name: ORM check
        run: python scripts/minimaws/minimaws.py load --executable ./mame --softwarepath hash
      - uses: actions/upload-artifact@master
        with:
          name: mame-linux-${{ matrix.compiler }}-${{ github.sha }}
          path: mame
