name: XML validation

on:
  push:
    paths:
    - 'hash/*'
  pull_request:
    paths:
    - 'hash/*'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxml2-utils
    - name: Validate (HSI)
      run: for x in hash/*.hsi ; do xmllint --noout "$x" ; done
    - name: Validate (XML)
      run: for x in hash/*.xml ; do xmllint --noout --valid "$x" ; done
